### ISSUE TITLE
Create R package for GenSVM

### ISSUE THREAD

**Issue by GjjvdBurg** [GjjvdBurg/GenSVM#2]
An R package for using GenSVM is planned. Please use this issue to express your interest in such a package by [leaving a :+1: reaction to this issue](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments), thanks!

**Comment by CBravoR** [comment]
👍

**Comment by GjjvdBurg** [comment]
Here it is: https://github.com/GjjvdBurg/RGenSVM
